export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const CHANGE_EMPLOYEE_COUNT = "CHANGE_EMPLOYEE_COUNT";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const SET_EDITING_EMPLOYEE = "SET_EDITING_EMPLOYEE"
export const SAVE_EDITED_EMPLOYEE = "SAVE_EDITED_EMPLOYEE"